cs631_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^personnel/', include('personnel.urls')),
    url(r'^patient/', include('patient.urls')),

    # /physicians/add/
    url(r'physicians/add/$', RedirectView.as_view(pattern_name='index', permanent=False), name='physician-add-redir'),
]

patient/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

app_name = 'patient'

urlpatterns = [
    # /patient/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /patient/employee_no
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /patients/add/
    url(r'add/$', views.PatientCreate.as_view(), name='patient-add'),
]

personnel/urls.py
from django.conf.urls import url
from . import views
from django.views.generic.base import RedirectView

app_name = 'personnel'

urlpatterns = [
    # /personnel/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /personnel/physicians
    url(r'physicians/$', views.PhysiciansView.as_view(), name='physicians'),

    # /personnel/surgeons
    url(r'surgeons/$', views.SurgeonsView.as_view(), name='surgeons'),

    # /personnel/nurses
    url(r'nurses/$', views.NursesView.as_view(), name='nurses'),

    # /personnel/employee_no
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /personnel/physicians/employee_no
    # url(r'physicians/^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'physicians/^(?P<pk>[0-9]+)/$', RedirectView.as_view(pattern_name='detail', permanent=False), name='physician_detail'),

    # /personnel/shift/
    url(r'shift/$', views.get_shift_info, name='shift-add'),

    # /personnel/physicians/add/
    url(r'physicians/add/$', views.get_physician_info, name='physician-add'),

    # /personnel/physicians/availability/
    url(r'physicians/availability/$', views.get_physician_shift_info, name='get-physician-avail'),

    # /personnel/physicians/availability/employee_no/
    #url(r'physicians/availability/(?P<pk>[0-9]+)/$', views.DatesDetailView.as_view(), name='physician_dates'),
    url(r'physicians/availability/(?P<pk>[0-9]+)/$', views.get_physician_date, name='physician_dates'),

    # /personnel/physicians/availability/employee_no/date/
    #url(r'physicians/availability/(?P<employee_no_id>\d+)/(?P<date>\d{4}-\d{2}-\d{2})/$', views.AvailView.as_view(), name='physician_avail'),
    url(r'physicians/availability/(?P<employee_no_id>\d+)/(?P<date>\d{4}-\d{2}-\d{2})/$', views.get_appointment_selection, name='physician_avail'),

    # /personnel/physicians/availability/book_appointment/
    url(r'physicians/availability/book/$', views.get_appointment_selection, name='book_appointment'),

    # /personnel/surgeons/add/
    url(r'surgeons/add/$', views.get_surgeon_info, name='surgeon-add'),

    # /personnel/nurses/add/
    url(r'nurses/add/$', views.get_nurse_info, name='nurse-add'),

]

personnel/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.

'''
When creating new models, remember to do the following:
1. include app in settings.py --> INSTALLED_APPS
2. python manage.py makemigrations (app name)
3. python manage.py migrate
'''


class Personnel(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    gender = models.CharField(max_length=1) # M or F
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=12)
    salary = models.IntegerField()
    ssn = models.IntegerField()

    def get_absolute_url(self):
        return reverse('personnel:detail', kwargs={'pk': self.pk})

    def __str__(self):
         return self.first_name + ' ' + self.last_name


class PhysicianManager(models.Manager):
    def create_physician(self):
        from django.db import connection
        with connection.cursor() as cursor:
            cursor.execute("""
                INSERT INTO `test_1`.`personnel_personnel` (`first_name`, `last_name`, `gender`, `address`, `phone`,
                 `salary`, `ssn`) 
	                VALUES ('Carl', 'Dio', 'M', '3 Street', 1234567892, 105000,545667456)
                """)
            cursor.execute("""
                SELECT *
                FROM `test_1`.`personnel_personnel` personnel
                WHERE personnel.id = LAST_INSERT_ID()
                """)

            result_list = []
            row = cursor.fetchone()
            result_list.append(row)

            cursor.execute("""
                INSERT INTO `test_1`.`personnel_physician`(`specialty`, `employee_no_id`)
                    VALUES('Cardiologist', LAST_INSERT_ID())
                """)
            cursor.execute("""
                SELECT physician.specialty
                FROM `test_1`.`personnel_physician` physician
                WHERE personnel.id = LAST_INSERT_ID()
                """)

            row = cursor.fetchone()
            result_list.append(row)

        return result_list


class Physician(models.Model):
    employee_no = models.OneToOneField(Personnel, on_delete=models.CASCADE, primary_key=True)
    specialty = models.CharField(max_length=50)

    objects = PhysicianManager()

    #def get_absolute_url(self):
    #    return reverse('personnel:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.employee_no)


class Surgeon(models.Model):
    employee_no = models.OneToOneField(Personnel, on_delete=models.CASCADE, primary_key=True)
    specialty = models.CharField(max_length=50)
    contract_type = models.CharField(max_length=20)
    #contract_length = models.DateField('contract_length', blank=True, null=True)
    #surgery_type_no = models.IntegerField()

    def __str__(self):
        return str(self.employee_no)


class Nurse(models.Model):
    employee_no = models.OneToOneField(Personnel, on_delete=models.CASCADE, primary_key=True)
    grade = models.CharField(max_length=1)  # A, B, C, D, E, F
    years_exp = models.IntegerField()

    def __str__(self):
        return str(self.employee_no)


class Shift(models.Model):
    date = models.DateField()
    employee_no = models.ForeignKey(Personnel, on_delete=models.CASCADE)
    working_ind = models.BooleanField()

    class Meta:
        unique_together = ('date', 'employee_no')

    def __str__(self):
        return str(self.date)


class Schedule(models.Model):
    shift_no = models.OneToOneField(Shift, on_delete=models.CASCADE)
    block1 = models.BooleanField()
    block2 = models.BooleanField()
    block3 = models.BooleanField()
    block4 = models.BooleanField()
    block5 = models.BooleanField()
    block6 = models.BooleanField()
    block7 = models.BooleanField()
    block8 = models.BooleanField()


class TimeBlock(models.Model):
    shift_no = models.ForeignKey(Shift, on_delete=models.CASCADE)
    time = models.CharField(max_length=20)
    attending = models.BooleanField()

    def __str__(self):
        return str(self.time)

personnel/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.db import transaction
from .models import Personnel, Physician, Surgeon, Nurse, Shift, Schedule, TimeBlock
from localflavor.us.forms import USPhoneNumberField
from extra_views import CreateWithInlinesView, InlineFormSet
#from .forms import PhysicianFormSet
#from .forms import PhysicianForm
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from .forms import PhysicianForm, SurgeonForm, NurseForm, ShiftForm, PhysicianGetShiftForm, PhysicianSelectTimeForm, PhysicianGetDateForm
from . import values
import datetime



class IndexView(generic.ListView):
    template_name = 'personnel/index.html'
    context_object_name = 'all_personnel'

    def get_queryset(self):
        return Personnel.objects.all()


class PhysiciansView(generic.ListView):
    template_name = 'personnel/physicians.html'
    context_object_name = 'all_physicians'

    def get_queryset(self):
        #return Physician.objects.all()
        #return Physician.objects.select_related('employee_no').values('employee_no_id')
        return Physician.objects.select_related('employee_no')


class SurgeonsView(generic.ListView):
    template_name = 'personnel/surgeons.html'
    context_object_name = 'all_surgeons'

    def get_queryset(self):
        return Surgeon.objects.select_related('employee_no')


class NursesView(generic.ListView):
    template_name = 'personnel/nurses.html'
    context_object_name = 'all_nurses'

    def get_queryset(self):
        return Nurse.objects.select_related('employee_no')


class DetailView(generic.DetailView):
    model = Personnel
    template_name = 'personnel/detail.html'

    #context_object_name = 'personnel_list'
    # def get_context_data(self, **kwargs):
    #     context = super(DetailView, self).get_context_data(**kwargs)
    #     context.update({
    #         'personnel_list': Physician.objects.all(),
    #         'personnel': Personnel.objects.all()
    #     })
    #     return context

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        try:
            context['physician'] = Physician.objects.get(employee_no_id=self.kwargs['pk'])
        except Physician.DoesNotExist:
            context['physician'] = None

        try:
            context['surgeon'] = Surgeon.objects.get(employee_no_id=self.kwargs['pk'])
        except Surgeon.DoesNotExist:
            context['surgeon'] = None

        try:
            context['nurse'] = Nurse.objects.get(employee_no_id=self.kwargs['pk'])
        except Nurse.DoesNotExist:
            context['nurse'] = None

        return context

    def get_queryset(self):
        return Personnel.objects.all()


class PersonnelCreate(CreateView):
    model = Personnel
    template_name = 'personnel/personnel_form.html'
    phone = USPhoneNumberField()
    fields = ['first_name', 'last_name', 'gender', 'address', 'phone', 'salary', 'ssn']
#
#     def form_valid(self, form):
#         # Get a new object based on the form
#         self.object = form.save(commit=False)
#         self.object.save()
#
#         # Use new object to assign to second model
#         physician_info = Physician(employee_no=self.object, )
#         physician_info.save()
#
#         return HttpResponseRedirect(self.get_absolute_url)

# class PersonnelPhysicianCreate(CreateView):
#     model = Personnel
#     template_name = 'personnel/personnel_form.html'
#     phone = USPhoneNumberField()
#     fields = ['first_name', 'last_name', 'gender', 'address', 'phone', 'salary', 'ssn']
#
#     def get_context_data(self, **kwargs):
#         data = super(PersonnelPhysicianCreate, self).get_context_data(**kwargs)
#         if self.request.POST:
#             data['physician'] = PhysicianFormSet(self.request.POST, instance=self.object)
#         else:
#             data['physician'] = PhysicianFormSet(instance=self.object)
#         return data
#
#     def form_valid(self, form):
#         context = self.get_context_data()
#         physician = context['physician']
#         with transaction.atomic():
#             self.object = form.save()
#
#             if physician.is_valid():
#                 physician.instance = self.object
#                 physician.save()
#         return super(PersonnelPhysicianCreate, self).form_valid(form)


# class PhysicianInline(InlineFormSet):
#     model = Physician
#     fields = '__all__'

# class PhysicianCreate(CreateWithInlinesView):
#     model = Personnel
#     inlines = [PhysicianInline]
#     fields = '__all__'
#     template_name = 'personnel/personnel_form.html'

# class PersonnelCreate(CreateView):
#     model = Personnel
#     template_name = 'personnel/personnel_form.html'
#     phone = USPhoneNumberField()
#     fields = ['first_name', 'last_name', 'gender', 'address', 'phone', 'salary', 'ssn']
#
# class PhysicianCreate(CreateView):
#     model = Physician
#     template_name = 'personnel/personnel_form.html'
#     fields = ['specialty']

# def physicianView(request):
#     if request.method == 'POST':
#         form = PhysicianForm(request.POST)
#         if form.is_valid():
#             first_name = request.POST.get('first_name', '')
#             last_name = request.POST.get('last_name', '')
#             gender = request.POST.get('gender', '')
#             address = request.POST.get('address', '')
#             phone = request.POST.get('phone', '')
#             salary = request.POST.get('salary', '')
#             ssn = request.POST.get('ssn', '')
#             specialty = request.POST.get('specialty', '')
#
#             personnel_obj = Personnel(first_name = first_name, last_name = last_name, gender = gender,
#                                      address = address, phone = phone, salary = salary, ssn = ssn)
#             personnel_obj.save()
#
#             physician_obj = Physician(employee_no_id = personnel_obj, specialty = specialty)
#             physician_obj.save()
#
#             return HttpResponseRedirect(reverse('personnel:index'))
#
#         else:
#            form = PhysicianForm()
#
#         return render(request, 'personnel/personnel_form.html', {'form': form})

def get_physician_info(request):
    if request.method == 'POST':
        form = PhysicianForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            gender = form.cleaned_data['gender']
            address = form.cleaned_data['address']
            phone = form.cleaned_data['phone']
            salary = form.cleaned_data['salary']
            ssn = form.cleaned_data['ssn']
            specialty = form.cleaned_data['specialty']

            personnel = Personnel(first_name=first_name, last_name=last_name, gender=gender, address=address,
                                  phone=phone, salary=salary, ssn=ssn)
            personnel.save()

            physician = Physician(employee_no_id=personnel.id, specialty=specialty)
            physician.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('personnel:index'))
        else:
            print(form.errors)

    else:
        form = PhysicianForm()

    return render(request, 'personnel/physician_form.html', {'form': form})


def get_surgeon_info(request):
    if request.method == 'POST':
        form = SurgeonForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            gender = form.cleaned_data['gender']
            address = form.cleaned_data['address']
            phone = form.cleaned_data['phone']
            salary = form.cleaned_data['salary']
            ssn = form.cleaned_data['ssn']
            specialty = form.cleaned_data['specialty']
            contract_type = form.cleaned_data['contract_type']
            # contract_length = form.cleaned_data['contract_type']

            personnel = Personnel(first_name=first_name, last_name=last_name, gender=gender, address=address,
                                  phone=phone, salary=salary, ssn=ssn)
            personnel.save()

            surgeon = Surgeon(employee_no_id=personnel.id, specialty=specialty, contract_type=contract_type, )
            surgeon.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('personnel:index'))
        else:
            print(form.errors)

    else:
        form = SurgeonForm()

    return render(request, 'personnel/surgeon_form.html', {'form': form})


def get_nurse_info(request):
    if request.method == 'POST':
        form = NurseForm(request.POST)
        if form.is_valid():
            # process the data in form.cleaned_data as required
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            gender = form.cleaned_data['gender']
            address = form.cleaned_data['address']
            phone = form.cleaned_data['phone']
            salary = form.cleaned_data['salary']
            ssn = form.cleaned_data['ssn']
            grade = form.cleaned_data['grade']
            years_exp = form.cleaned_data['years_exp']

            personnel = Personnel(first_name=first_name, last_name=last_name, gender=gender, address=address,
                                  phone=phone, salary=salary, ssn=ssn)
            personnel.save()

            nurse = Nurse(employee_no_id=personnel.id, grade=grade, years_exp=years_exp)
            nurse.save()

            # redirect to a new URL:

personnel/templates/personnel/availability.html
{% extends 'personnel/base.html' %}
{% block title %}Doctor Availability{% endblock %}

{% block body %}

    <h3>Availability on {{ object.date }}</h3>

    <div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                        {% if schedule %}
                        <form class="form-horizontal" action="/personnel/" method="post" enctype="multipart/form-data">

                            <h4>Select a time for your appointment:</h4>

                            {% if not schedule.block1 %}
                            <p><input type="radio" name="block" value="block1"> 9am - 10am</p>
                            {% endif %}

                            {% if not schedule.block2 %}
                            <p><input type="radio" name="block" value="block2">10am - 11am</p>
                            {% endif %}

                            {% if not schedule.block3 %}
                            <p><input type="radio" name="block" value="block3">11am - 12pm</p>
                            {% endif %}

                            {% if not schedule.block4 %}
                            <p><input type="radio" name="block" value="block4">12pm -  1pm</p>
                            {% endif %}

                            {% if not schedule.block5 %}
                            <p><input type="radio" name="block" value="block5"> 1pm -  2pm</p>
                            {% endif %}

                            {% if not schedule.block6 %}
                            <p><input type="radio" name="block" value="block6"> 2pm -  3pm</p>
                            {% endif %}

                            {% if not schedule.block7 %}
                            <p><input type="radio" name="block" value="block7"> 3pm -  4pm</p>
                            {% endif %}

                            {% if not schedule.block8 %}
                            <p><input type="radio" name="block" value="block8"> 4pm -  5pm</p>
                            {% endif %}

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>

                        </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    {% else %}
    <h5> Not working today </h5>
    {% endif %}

{% endblock %}

personnel/templates/personnel/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Newark Medical Associates{% endblock %}</title>

    <!--Loads the path to your static files-->
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'personnel/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!--Logo-->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Newark Medical Associates</a>
            </div>

            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          Personnel Management
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><a href="{% url 'personnel:index' %}">All Personnel</a></li>
                          <li><a href="{% url 'personnel:physicians' %}">Our Physicians</a></li>
                          <li><a href="{% url 'personnel:surgeons' %}">Our Surgeons</a></li>
                          <li><a href="{% url 'personnel:nurses' %}">Our Nurses</a></li>
                          <li><a href="{% url 'personnel:shift-add' %}">Schedule Job Shifts</a></li>
                      </ul>
                    </li>

                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          Patient Management
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><a href="{% url 'patient:index' %}">All Patients</a></li>
                          <li><a href="{% url 'personnel:get-physician-avail' %}">Schedule an Appointment</a></li>
                      </ul>
                    </li>

                    <li class="dropdown">
                      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                          In-Patient Management
                          <span class="caret"></span>
                      </a>
                      <ul class="dropdown-menu">
                          <li><a href="#">Patient Room and Bed</a></li>
                          <li><a href="#">Manage Patient's Physician</a></li>
                          <li><a href="#">Manage Patient's Nurse</a></li>
                          <li><a href="#">Book a Surgery</a></li>
                          <li><a href="#">View Surgery Room Availability</a></li>
                          <li><a href="#">View Surgeon's Schedule</a></li>
                          <li><a href="#">View Patient's Scheduled Surgeries</a></li>
                      </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'personnel:physician-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; New Physician
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'personnel:surgeon-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; New Surgeon
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'personnel:nurse-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; New Nurse
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'patient:patient-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; New Patient
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>

                <!--<ul class="nav navbar-nav navbar-right">-->
                    <!--<li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>-->
                    <!--<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>-->
                <!--</ul>-->
            </div>

        </div>
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

personnel/templates/personnel/detail.html
{% extends 'personnel/base.html' %}
{% block title %}Personnel - {{ object }}{% endblock %}

{% block body %}

    <h3>{{ object.first_name }} {{ object.last_name }}</h3>

    <ul>
        <li>Gender: {{ object.gender }}</li>
        <li>Address: {{ object.address }}</li>
        <li>Phone: {{ object.phone }}</li>
        <li>Salary: ${{ object.salary }}</li>
        <li>SSN: {{ object.ssn }}</li>

        {% if physician %}
        <li>Specialty: {{ physician.specialty }}</li>

        {% elif surgeon %}
        <li>Specialty: {{ surgeon.specialty }}</li>
        <li>Contract Type: {{ surgeon.contract_type }}</li>
        <!--INSERT CONTRACT LENGTH HERE-->

        {% elif nurse %}
        <li>Grade: {{ nurse.grade }}</li>
        <li>Years of Experience: {{ nurse.years_exp }}</li>
        {% endif %}
    </ul>

{% endblock %}

personnel/templates/personnel/get_physician_shift_form.html
{% extends 'personnel/base.html' %}
{% block title %}Doctor Availability{% endblock %}
{% block personnel_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="/personnel/physicians/availability/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% if form.errors %}
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endfor %}
                            {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                            {% endfor %}
                        {% endif %}

                        <h3>Select a Doctor:</h3>

                        {{ form.as_p }}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

personnel/templates/personnel/index.html
{% extends 'personnel/base.html' %}
{% block title %}All Personnel{% endblock %}

{% block body %}
    <h3>All Personnel:</h3>
    {% if all_personnel %}
        <ol>
            {% for personnel in all_personnel %}
            <li><a href="{% url 'personnel:detail' personnel.id %}">{{ personnel.first_name }} {{ personnel.last_name }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <h5>No personnel registered</h5>
    {% endif %}
{% endblock %}

personnel/templates/personnel/nurses.html
{% extends 'personnel/base.html' %}
{% block title %}Our Nurses{% endblock %}

{% block body %}
    <h3>Our Nurses:</h3>
    {% if all_nurses %}
        <ol>
            {% for nurse in all_nurses %}
                <li><a href="{% url 'personnel:detail' nurse.employee_no_id %}">{{ nurse }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <h5>No nurses registered</h5>
    {% endif %}
{% endblock %}

personnel/templates/personnel/personnel-form-template.html
{% for field in form.visible_fields %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

personnel/templates/personnel/personnel_form.html
{% extends 'personnel/base.html' %}
{% block title %}Input Personnel Information{% endblock %}
{% block personnel_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'personnel/personnel-form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

personnel/templates/personnel/shift_dates.html
{% extends 'personnel/base.html' %}
{% block title %}All Available Dates{% endblock %}

{% block body %}
    <h3>All Available Dates for {{ personnel.first_name }} {{ personnel.last_name }}:</h3>
    {% if all_dates %}
        <ol>
            {% for date in all_dates %}
            <li><a href="{% url 'personnel:physician_avail' employee_no_id=personnel.id date=date.date|date:'Y-m-d' %}">{{ date.date }}</a></li>
            {% endfor %}
        </ol>
    {% else %}
        <h5>No dates available</h5>
    {% endif %}
{% endblock %}